### ISSUE TITLE
How To Preload Zip?

### ISSUE THREAD

**Issue by 4kh00** [nbarkhina/DosWasmX#4]
Hi! I have a disk image that I want to have users see when the app is loaded. You explain this in the documentation. However, I also want to run a command automatically on machine load. How would I do this? Thank you!

**Comment by nbarkhina** [comment]
Hi @4kh00 - what you can do is edit script.js on line 806 and add commands here - 
make sure each command is separated by `\r\n` 

![image](https://github.com/nbarkhina/DosWasmX/assets/10982154/9d2bc0e6-984e-494a-9074-4d1bd9ea1f90)

**Comment by nbarkhina** [comment]
more like this -
```javascript
{
responseText = responseText.replace('[autoexec]',
'[autoexec]\r\nimgmount c "' + this.base_name +
'.img"\r\n' + multiFileScript + 'boot c:' + '\r\ncd oregon\r\noregon.exe');
}
```
